export const SWIPE_LEFT_MONEY_TOTAL_MIN_DISTANCE = 60
export const SWIPE_RIGHT_MONEY_TOTAL_MIN_DISTANCE = 60

export const SWIPE_TRANSITION_DELAY_MS = 150
export const SWIPE_TRANSITION_DELAY_S = SWIPE_TRANSITION_DELAY_MS / 1000